version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=test-grpc-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    command:
#      - /bin/bash
#        - -c
#        - |
#        psql -U postgres -d template1 -f /docker-entrypoint-initdb.d/init.sql -e POSTGRES_PASSWORD=root
volumes:
  postgres_data: { }
